### ISSUE TITLE
Exported Content Reuse and Human Readable Format Conventions

### ISSUE THREAD

**Issue by pdpinch** [openedx/blockstore#22]
This issue is branched off from https://github.com/open-craft/blockstore/issues/19#issuecomment-440393721 and is to discuss a particular use case for exporting course content. 

As a course owner, I have had need to export a course and then extract certain components of it, like a sequence, a unit or even a problem. Sometimes I extract these components to build a new course, for example, to create a survey course out of deep, extensive course. Sometimes I extract these components because I want to import them (as a sequence, unit or problem) into another application altogether, like DART.

**Comment by pdpinch** [comment]
the specific question that lead me to write up this use case was when @ormsbee was proposing that in an export. the static files might be located in a separate tree from the rest of the content. This could be an inconvenience for a user who was trying to extract a unit or problem from a larger course (or bundle?) because they would need to located material from two locations. 

Having a clear relationship between the two trees would certainly help, although it might be less clear when it comes to re-used content. For example, problem1 and problem2 might both reference the same static image, image3. When I want to pull out problem2, it may not be obvious where to find it's corresponding assets because they won't be at the static/problem2 but rather at static/image3

That all said, this may be handled well enough by explicit linking. And even having separate tree with directories for static assets would be an improvement over the current state.

**Comment by ormsbee** [comment]
@pdpinch: I feel like there's a tension in terms of individual leaf tracking and making the format something pleasant to use for course level editing, but I could be completely off-base there.

The intuitive thing for a single capa problem would be something like:

```
problem.xml
static/
          figure_a.png
          figure_b.png
```

That maps pretty much 1:1 to what the Bundle for that problem would look like. But doing that for every leaf node means that the course is broken down into extremely granular chunks -- which is acceptable for a machine format, but frustrating for humans. Every HTML element, inline discussion module, etc. would be separate directory, often with a single one line file in it. So I thought what would be useful at that level was a way to make the granularity of the human-written XML freeform, so you could do something like:

```xml
<unit>
    <video usage="blockstore_intro" display_name="Introduction to Blockstore"
           html5_sources="static/OpenEdX-Blockstore/BlockstoreIntro.m3u8" />
    <html usage="blockstore_intro_description">
        <![CDATA[
            <p>Blockstore is <b>so much fun</b>.</p>
        ]]>
    </html>
    <xi:include href="blockstore/problems/why_blockstore.xml" />
    <discussion usage="blockstore_talk" topic="blockstore" />
</unit>
```

In the above example, the `<video>` tag and the included Capa problem would both make references to their own static assets. The `<html>` tag uses CDATA to pull stuff inline, but it could have just as easily been included either as a whole or with just the tag here and an HTML document in the `include`. It won't be possible to know what's appropriate for every XBlock type, and even the same XBlock (e.g. video) could use or not use its own static assets depending on the situation. Using the `include` directive gives authors more flexibility in how they want to organize their content for readability, but it means that it all gets compiled to a giant XML doc in the end -- which simplifies parsing in many ways, but it means that we have to have a separate convention for where we put all the block-specific assets.

That's why I suggested that we have a separate `static` directory. Because if we're allowing XML to be potentially inline to prevent having thousands of directories, we need some place to put the assets in a consistently addressable way. And since doing `include` compiles out to a giant `course.xml` file, having local directories of files gets cumbersome (you don't know where the fragment came from). But it is relatively straightforward to do a mapping from the tree of static assets to the Bundle-local version.

This of course rests on the giant assumption that having a flexible way to structure the XML is itself a valuable thing. But I do like it because it seems like a relatively simple way to normalize our data for any command line tooling we have.

**Comment by bradenmacdonald** [comment]
> As a course owner, I have had need to export a course and then extract certain components of it, like a sequence, a unit or even a problem. Sometimes I extract these components to build a new course, for example, to create a survey course out of deep, extensive course. Sometimes I extract these components because I want to import them (as a sequence, unit or problem) into another application altogether, like DART.

@pdpinch Do you think in the future this workflow might change so that instead of "export and extract", such course owners would adopt a more "Blockstore-style" approach of simply linking to those existing components, rather than creating a copy? (Maybe doing a copy-on-write later , but what's the reason to copy and break the history prematurely?)

Same thing applies to DART - my hope is that if they adapt to the new architecture there will be no need to copy the assets to a separate server/anything, and that they can also stop using LTI and use a more direct embedding format if they want.

Or are you specifically talking about teams that do git-based authoring?

@ormsbee 

> The intuitive thing for a single capa problem would be something like

That looks so much nicer than a shared `static` folder :)

> This of course rests on the giant assumption that having a flexible way to structure the XML is itself a valuable thing. But I do like it because it seems like a relatively simple way to normalize our data for any command line tooling we have.

I think the flexible XML can do more harm than good. I'm still catching up on the latest discussion threads here, but I'm kind of liking the idea of a strict computer-friendly format within blockstore and a more flexible human-friendly precursor format than can be imported to blockstore but is not used directly within blockstore.
