### ISSUE TITLE
Separating Policy from Content

### ISSUE THREAD

**Issue by ormsbee** [openedx/blockstore#35]
@bradenmacdonald, @symbolist: 

One of the things we've discussed has been separating content (e.g. text of a problem) from policy (e.g. due date). That distinction gets murky in a lot of places, as we have things like CCX or policies that might only apply to specific block types at the moment, like capa randomization settings.

At the Open edX 2019 conference, @Colin-Fredericks mentioned his tool for policy modifications to a course, which I think is a useful place to look for some real-world-tested solutions to this problem: https://github.com/Colin-Fredericks/hx-xml

A really interesting point to me is that the selection criteria in these scripts can be a lot more sophisticated than some of the conversations we were having in the past. We talked about setting things on a block-type/assignment-type basis, but here we have rules that introspect details about a problem such as the following logic for [setting max attempts](https://github.com/Colin-Fredericks/hx-xml/blob/master/SetMaxAttemptsIfGraded.py#L11-L24):

```
Your options for the number are:
  - An actual number, which sets all problems to the same # of attempts
  - "delete" or "default", which removes the value so that
    course-wide default takes over
  - "auto" (recommended), in which case attempts are set as follows:
    - Numerical and Formula problems get 10
    - Customresponse and Text problems get 5
    - Checkbox problems get a number of attempts equal to the number of choices, max 5.
    - MC problems get...
      - 3 if they have 7+ options
      - 2 if they have 4-6 options
      - 1 if they have 2-3 options
    - Multi-problems get the highest number of the set.
    - Other problem types are skipped.
```

I'm making this issue as a place to discuss how we can support this sort of separation on the Blockstore side. I imagine we'll get to this after Links and some of the XBlock runtime work in flight, but I wanted to pin it so we don't forget.

**Comment by bradenmacdonald** [comment]
Nice. If we can make that more generic, it's the sort of approach I had in mind (although as you've said, this is more sophisticated).

**Comment by Colin-Fredericks** [comment]
Thanks for tagging me in.

Let me give a few examples of why course designers set various pieces of assignment policy:
* Due Date is based on a problem's location in the course (week 1, week 2, etc.)
* Show Answer is based on a problem's purpose
* Weight and Number of Attempts are based on a problem's purpose and difficulty level

Difficult level is inherently tied to the text of the problem, and *should not be quantized as a piece of policy* because it's context-dependent.

By "purpose" I mean whether it's intended as summative, formative, practice, whether it's an exercise or piece of instruction *masquerading* as a question, whether it's an intentional trick question, etc. Purpose may be impossible to determine based on *just* the text - both context and authorial intent matter.

However: none of this means you need to avoid separating these things in the course structure. For scripting purposes, we just need a reliable way to access both of them - a JSON policy needs to point unambiguously at the problem's XML, so that we can determine its features and location. (I would assume that you need that anyway.)

**Comment by bradenmacdonald** [comment]
This is old and most likely no longer relevant to the near term development of blockstore, so I'm going to close it. The discussion will be preserved on GitHub for future reference if useful, e.g. to the learning core work.
