### ISSUE TITLE
Signing in to blockstore raise an error of invalid scope

### ISSUE THREAD

**Issue by oma0256** [openedx/blockstore#75]
I have my open edx devstack setup as well my blockstore containers running as well. I'm following this guide here to configure blockstore for my devstack instance https://github.com/edx/blockstore#using-with-docker-devstack. I have configured sso to be able to login into blockstore, however I get an invalid scope error. Below are screenshots to my configurations.
**oauth2_provider**
![Screenshot 2020-08-07 at 11 39 16](https://user-images.githubusercontent.com/14260655/89628446-f97a4f00-d8a4-11ea-97ad-a2521c639d9a.png)

**oauth_dispatch**
![Screenshot 2020-08-07 at 11 39 43](https://user-images.githubusercontent.com/14260655/89628471-0303b700-d8a5-11ea-92c2-0d3fdf8443ca.png)

**private.py**
![Screenshot 2020-08-07 at 11 44 00](https://user-images.githubusercontent.com/14260655/89628506-0dbe4c00-d8a5-11ea-8bbb-354632247401.png)

**settings.py**
![Screenshot 2020-08-07 at 11 45 27](https://user-images.githubusercontent.com/14260655/89628535-17e04a80-d8a5-11ea-809c-724eae1a25b1.png)

After visiting `http://159.89.49.124:18250/login` I'm redirected to `http://159.89.49.124:18000/oauth2/authorize?redirect_uri=http%3A%2F%2F159.89.49.124%3A18250%2Fcomplete%2Fedx-oauth2%2F%3Fredirect_state%3DBH9V61XLz768nPnxpcfX5Piu7MRHYgBb&client_id=blockstore-sso-key&response_type=code&state=BH9V61XLz768nPnxpcfX5Piu7MRHYgBb&scope=user_id+profile+email` which throws an `invalid scope` error, not sure why my scope is being set to `user_id+profile+email` yet I configured it to just `user_id`. Tried updating my scope to `user_id,profile,email` in the second screenshot however I still get the same error of invalid scope any help will be much appreciated thank you.

**Comment by bradenmacdonald** [comment]
@oma0256 Sorry for the delay in replying. I don't see anything obviously wrong in your setup, so I'm not sure what the issue is. I just configured blockstore SSO on my devstack following the README instructions and can confirm it's working.

The redirect URL that I get is `http://localhost:18000/oauth2/authorize?redirect_uri=http%3A%2F%2Flocalhost%3A18250%2Fcomplete%2Fedx-oauth2%2F%3Fredirect_state%3DsQxqIgBjHcmUkPoI5akzfl9HKcffvh0y&scope=user_id+profile+email&response_type=code&client_id=blockstore-sso-key&state=sQxqIgBjHcmUkPoI5akzfl9HKcffvh0y` and that works.

Just `user_id` is correct for the ApplicationAccess configuration; the email and profile scopes don't require additional permissions.


A few thoughts:
* Make sure your devstack is edx-platform `master` and not Ironwood or any named release version.
* The way you're running your devstack on another IP instead of on `localhost` may be causing an issue.
* You included a screenshot of `settings.py` - what file is that? You only need to configure `private.py` in blockstore, and there is no `settings.py` file used by Blockstore.

**Comment by bradenmacdonald** [comment]
Oh and by the way, you can still use Blockstore without the SSO working; you don't need to be able to log into its web interface in order to use it for content libraries.
